/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PlayRouteImport } from './routes/play'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountOauthErrorRouteImport } from './routes/account/oauth-error'
import { Route as AccountPasswordResetRouteImport } from './routes/account/password-reset'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsAttributionRouteImport } from './routes/docs/attribution'
import { Route as DocsPrivacyPolicyRouteImport } from './routes/docs/privacy-policy'
import { Route as UserUserIdRouteImport } from './routes/user/$userId'
import { Route as AccountSettingsAvatarRouteImport } from './routes/account/settings/avatar'
import { Route as AccountSettingsSecurityRouteImport } from './routes/account/settings/security'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOauthErrorRoute = AccountOauthErrorRouteImport.update({
  id: '/account/oauth-error',
  path: '/account/oauth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPasswordResetRoute = AccountPasswordResetRouteImport.update({
  id: '/account/password-reset',
  path: '/account/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAttributionRoute = DocsAttributionRouteImport.update({
  id: '/docs/attribution',
  path: '/docs/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPrivacyPolicyRoute = DocsPrivacyPolicyRouteImport.update({
  id: '/docs/privacy-policy',
  path: '/docs/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsAvatarRoute = AccountSettingsAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsSecurityRoute = AccountSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/play': typeof PlayRoute
  '/search': typeof SearchRoute
  '/styleguide': typeof StyleguideRoute
  '/account/login': typeof AccountLoginRoute
  '/account/oauth-error': typeof AccountOauthErrorRoute
  '/account/password-reset': typeof AccountPasswordResetRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/docs/attribution': typeof DocsAttributionRoute
  '/docs/privacy-policy': typeof DocsPrivacyPolicyRoute
  '/user/$userId': typeof UserUserIdRoute
  '/docs/': typeof DocsIndexRoute
  '/account/settings/avatar': typeof AccountSettingsAvatarRoute
  '/account/settings/security': typeof AccountSettingsSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/play': typeof PlayRoute
  '/search': typeof SearchRoute
  '/styleguide': typeof StyleguideRoute
  '/account/login': typeof AccountLoginRoute
  '/account/oauth-error': typeof AccountOauthErrorRoute
  '/account/password-reset': typeof AccountPasswordResetRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/docs/attribution': typeof DocsAttributionRoute
  '/docs/privacy-policy': typeof DocsPrivacyPolicyRoute
  '/user/$userId': typeof UserUserIdRoute
  '/docs': typeof DocsIndexRoute
  '/account/settings/avatar': typeof AccountSettingsAvatarRoute
  '/account/settings/security': typeof AccountSettingsSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/play': typeof PlayRoute
  '/search': typeof SearchRoute
  '/styleguide': typeof StyleguideRoute
  '/account/login': typeof AccountLoginRoute
  '/account/oauth-error': typeof AccountOauthErrorRoute
  '/account/password-reset': typeof AccountPasswordResetRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/docs/attribution': typeof DocsAttributionRoute
  '/docs/privacy-policy': typeof DocsPrivacyPolicyRoute
  '/user/$userId': typeof UserUserIdRoute
  '/docs/': typeof DocsIndexRoute
  '/account/settings/avatar': typeof AccountSettingsAvatarRoute
  '/account/settings/security': typeof AccountSettingsSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/play'
    | '/search'
    | '/styleguide'
    | '/account/login'
    | '/account/oauth-error'
    | '/account/password-reset'
    | '/account/register'
    | '/account/reset-password'
    | '/account/settings'
    | '/docs/attribution'
    | '/docs/privacy-policy'
    | '/user/$userId'
    | '/docs/'
    | '/account/settings/avatar'
    | '/account/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/play'
    | '/search'
    | '/styleguide'
    | '/account/login'
    | '/account/oauth-error'
    | '/account/password-reset'
    | '/account/register'
    | '/account/reset-password'
    | '/account/settings'
    | '/docs/attribution'
    | '/docs/privacy-policy'
    | '/user/$userId'
    | '/docs'
    | '/account/settings/avatar'
    | '/account/settings/security'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore'
    | '/play'
    | '/search'
    | '/styleguide'
    | '/account/login'
    | '/account/oauth-error'
    | '/account/password-reset'
    | '/account/register'
    | '/account/reset-password'
    | '/account/settings'
    | '/docs/attribution'
    | '/docs/privacy-policy'
    | '/user/$userId'
    | '/docs/'
    | '/account/settings/avatar'
    | '/account/settings/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  PlayRoute: typeof PlayRoute
  SearchRoute: typeof SearchRoute
  StyleguideRoute: typeof StyleguideRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountOauthErrorRoute: typeof AccountOauthErrorRoute
  AccountPasswordResetRoute: typeof AccountPasswordResetRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSettingsRoute: typeof AccountSettingsRouteWithChildren
  DocsAttributionRoute: typeof DocsAttributionRoute
  DocsPrivacyPolicyRoute: typeof DocsPrivacyPolicyRoute
  UserUserIdRoute: typeof UserUserIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/oauth-error': {
      id: '/account/oauth-error'
      path: '/account/oauth-error'
      fullPath: '/account/oauth-error'
      preLoaderRoute: typeof AccountOauthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/password-reset': {
      id: '/account/password-reset'
      path: '/account/password-reset'
      fullPath: '/account/password-reset'
      preLoaderRoute: typeof AccountPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/attribution': {
      id: '/docs/attribution'
      path: '/docs/attribution'
      fullPath: '/docs/attribution'
      preLoaderRoute: typeof DocsAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/privacy-policy': {
      id: '/docs/privacy-policy'
      path: '/docs/privacy-policy'
      fullPath: '/docs/privacy-policy'
      preLoaderRoute: typeof DocsPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/avatar': {
      id: '/account/settings/avatar'
      path: '/avatar'
      fullPath: '/account/settings/avatar'
      preLoaderRoute: typeof AccountSettingsAvatarRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/security': {
      id: '/account/settings/security'
      path: '/security'
      fullPath: '/account/settings/security'
      preLoaderRoute: typeof AccountSettingsSecurityRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
  }
}

interface AccountSettingsRouteChildren {
  AccountSettingsAvatarRoute: typeof AccountSettingsAvatarRoute
  AccountSettingsSecurityRoute: typeof AccountSettingsSecurityRoute
}

const AccountSettingsRouteChildren: AccountSettingsRouteChildren = {
  AccountSettingsAvatarRoute: AccountSettingsAvatarRoute,
  AccountSettingsSecurityRoute: AccountSettingsSecurityRoute,
}

const AccountSettingsRouteWithChildren = AccountSettingsRoute._addFileChildren(
  AccountSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  PlayRoute: PlayRoute,
  SearchRoute: SearchRoute,
  StyleguideRoute: StyleguideRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountOauthErrorRoute: AccountOauthErrorRoute,
  AccountPasswordResetRoute: AccountPasswordResetRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSettingsRoute: AccountSettingsRouteWithChildren,
  DocsAttributionRoute: DocsAttributionRoute,
  DocsPrivacyPolicyRoute: DocsPrivacyPolicyRoute,
  UserUserIdRoute: UserUserIdRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
