/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ImportRouteImport } from './routes/import'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountOauthErrorRouteImport } from './routes/account/oauth-error'
import { Route as AccountPasswordResetRouteImport } from './routes/account/password-reset'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsAttributionRouteImport } from './routes/docs/attribution'
import { Route as DocsPrivacyPolicyRouteImport } from './routes/docs/privacy-policy'
import { Route as EditIndexRouteImport } from './routes/edit/index'
import { Route as EditFilesRouteImport } from './routes/edit/files'
import { Route as QuiztivityEditRouteImport } from './routes/quiztivity/edit'
import { Route as QuiztivityPlayRouteImport } from './routes/quiztivity/play'
import { Route as UserUserIdRouteImport } from './routes/user/$userId'
import { Route as ViewQuizIdRouteImport } from './routes/view/$quizId'
import { Route as AccountSettingsAvatarRouteImport } from './routes/account/settings_/avatar'
import { Route as AccountSettingsSecurityRouteImport } from './routes/account/settings_/security'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOauthErrorRoute = AccountOauthErrorRouteImport.update({
  id: '/account/oauth-error',
  path: '/account/oauth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPasswordResetRoute = AccountPasswordResetRouteImport.update({
  id: '/account/password-reset',
  path: '/account/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAttributionRoute = DocsAttributionRouteImport.update({
  id: '/docs/attribution',
  path: '/docs/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPrivacyPolicyRoute = DocsPrivacyPolicyRouteImport.update({
  id: '/docs/privacy-policy',
  path: '/docs/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIndexRoute = EditIndexRouteImport.update({
  id: '/edit/',
  path: '/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditFilesRoute = EditFilesRouteImport.update({
  id: '/edit/files',
  path: '/edit/files',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiztivityEditRoute = QuiztivityEditRouteImport.update({
  id: '/quiztivity/edit',
  path: '/quiztivity/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiztivityPlayRoute = QuiztivityPlayRouteImport.update({
  id: '/quiztivity/play',
  path: '/quiztivity/play',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewQuizIdRoute = ViewQuizIdRouteImport.update({
  id: '/view/$quizId',
  path: '/view/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsAvatarRoute = AccountSettingsAvatarRouteImport.update({
  id: '/account/settings_/avatar',
  path: '/account/settings/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsSecurityRoute = AccountSettingsSecurityRouteImport.update({
  id: '/account/settings_/security',
  path: '/account/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/import': typeof ImportRoute
  '/play': typeof PlayRoute
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/styleguide': typeof StyleguideRoute
  '/account/login': typeof AccountLoginRoute
  '/account/oauth-error': typeof AccountOauthErrorRoute
  '/account/password-reset': typeof AccountPasswordResetRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/settings': typeof AccountSettingsRoute
  '/docs/attribution': typeof DocsAttributionRoute
  '/docs/privacy-policy': typeof DocsPrivacyPolicyRoute
  '/edit/files': typeof EditFilesRoute
  '/quiztivity/edit': typeof QuiztivityEditRoute
  '/quiztivity/play': typeof QuiztivityPlayRoute
  '/user/$userId': typeof UserUserIdRoute
  '/view/$quizId': typeof ViewQuizIdRoute
  '/docs/': typeof DocsIndexRoute
  '/edit/': typeof EditIndexRoute
  '/account/settings/avatar': typeof AccountSettingsAvatarRoute
  '/account/settings/security': typeof AccountSettingsSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/import': typeof ImportRoute
  '/play': typeof PlayRoute
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/styleguide': typeof StyleguideRoute
  '/account/login': typeof AccountLoginRoute
  '/account/oauth-error': typeof AccountOauthErrorRoute
  '/account/password-reset': typeof AccountPasswordResetRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/settings': typeof AccountSettingsRoute
  '/docs/attribution': typeof DocsAttributionRoute
  '/docs/privacy-policy': typeof DocsPrivacyPolicyRoute
  '/edit/files': typeof EditFilesRoute
  '/quiztivity/edit': typeof QuiztivityEditRoute
  '/quiztivity/play': typeof QuiztivityPlayRoute
  '/user/$userId': typeof UserUserIdRoute
  '/view/$quizId': typeof ViewQuizIdRoute
  '/docs': typeof DocsIndexRoute
  '/edit': typeof EditIndexRoute
  '/account/settings/avatar': typeof AccountSettingsAvatarRoute
  '/account/settings/security': typeof AccountSettingsSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/import': typeof ImportRoute
  '/play': typeof PlayRoute
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/styleguide': typeof StyleguideRoute
  '/account/login': typeof AccountLoginRoute
  '/account/oauth-error': typeof AccountOauthErrorRoute
  '/account/password-reset': typeof AccountPasswordResetRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/settings': typeof AccountSettingsRoute
  '/docs/attribution': typeof DocsAttributionRoute
  '/docs/privacy-policy': typeof DocsPrivacyPolicyRoute
  '/edit/files': typeof EditFilesRoute
  '/quiztivity/edit': typeof QuiztivityEditRoute
  '/quiztivity/play': typeof QuiztivityPlayRoute
  '/user/$userId': typeof UserUserIdRoute
  '/view/$quizId': typeof ViewQuizIdRoute
  '/docs/': typeof DocsIndexRoute
  '/edit/': typeof EditIndexRoute
  '/account/settings_/avatar': typeof AccountSettingsAvatarRoute
  '/account/settings_/security': typeof AccountSettingsSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/explore'
    | '/import'
    | '/play'
    | '/results'
    | '/search'
    | '/styleguide'
    | '/account/login'
    | '/account/oauth-error'
    | '/account/password-reset'
    | '/account/register'
    | '/account/reset-password'
    | '/account/settings'
    | '/docs/attribution'
    | '/docs/privacy-policy'
    | '/edit/files'
    | '/quiztivity/edit'
    | '/quiztivity/play'
    | '/user/$userId'
    | '/view/$quizId'
    | '/docs/'
    | '/edit/'
    | '/account/settings/avatar'
    | '/account/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/explore'
    | '/import'
    | '/play'
    | '/results'
    | '/search'
    | '/styleguide'
    | '/account/login'
    | '/account/oauth-error'
    | '/account/password-reset'
    | '/account/register'
    | '/account/reset-password'
    | '/account/settings'
    | '/docs/attribution'
    | '/docs/privacy-policy'
    | '/edit/files'
    | '/quiztivity/edit'
    | '/quiztivity/play'
    | '/user/$userId'
    | '/view/$quizId'
    | '/docs'
    | '/edit'
    | '/account/settings/avatar'
    | '/account/settings/security'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/explore'
    | '/import'
    | '/play'
    | '/results'
    | '/search'
    | '/styleguide'
    | '/account/login'
    | '/account/oauth-error'
    | '/account/password-reset'
    | '/account/register'
    | '/account/reset-password'
    | '/account/settings'
    | '/docs/attribution'
    | '/docs/privacy-policy'
    | '/edit/files'
    | '/quiztivity/edit'
    | '/quiztivity/play'
    | '/user/$userId'
    | '/view/$quizId'
    | '/docs/'
    | '/edit/'
    | '/account/settings_/avatar'
    | '/account/settings_/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  ImportRoute: typeof ImportRoute
  PlayRoute: typeof PlayRoute
  ResultsRoute: typeof ResultsRoute
  SearchRoute: typeof SearchRoute
  StyleguideRoute: typeof StyleguideRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountOauthErrorRoute: typeof AccountOauthErrorRoute
  AccountPasswordResetRoute: typeof AccountPasswordResetRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  DocsAttributionRoute: typeof DocsAttributionRoute
  DocsPrivacyPolicyRoute: typeof DocsPrivacyPolicyRoute
  EditFilesRoute: typeof EditFilesRoute
  QuiztivityEditRoute: typeof QuiztivityEditRoute
  QuiztivityPlayRoute: typeof QuiztivityPlayRoute
  UserUserIdRoute: typeof UserUserIdRoute
  ViewQuizIdRoute: typeof ViewQuizIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
  EditIndexRoute: typeof EditIndexRoute
  AccountSettingsAvatarRoute: typeof AccountSettingsAvatarRoute
  AccountSettingsSecurityRoute: typeof AccountSettingsSecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/oauth-error': {
      id: '/account/oauth-error'
      path: '/account/oauth-error'
      fullPath: '/account/oauth-error'
      preLoaderRoute: typeof AccountOauthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/password-reset': {
      id: '/account/password-reset'
      path: '/account/password-reset'
      fullPath: '/account/password-reset'
      preLoaderRoute: typeof AccountPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/attribution': {
      id: '/docs/attribution'
      path: '/docs/attribution'
      fullPath: '/docs/attribution'
      preLoaderRoute: typeof DocsAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/privacy-policy': {
      id: '/docs/privacy-policy'
      path: '/docs/privacy-policy'
      fullPath: '/docs/privacy-policy'
      preLoaderRoute: typeof DocsPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/': {
      id: '/edit/'
      path: '/edit'
      fullPath: '/edit/'
      preLoaderRoute: typeof EditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/files': {
      id: '/edit/files'
      path: '/edit/files'
      fullPath: '/edit/files'
      preLoaderRoute: typeof EditFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiztivity/edit': {
      id: '/quiztivity/edit'
      path: '/quiztivity/edit'
      fullPath: '/quiztivity/edit'
      preLoaderRoute: typeof QuiztivityEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiztivity/play': {
      id: '/quiztivity/play'
      path: '/quiztivity/play'
      fullPath: '/quiztivity/play'
      preLoaderRoute: typeof QuiztivityPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$quizId': {
      id: '/view/$quizId'
      path: '/view/$quizId'
      fullPath: '/view/$quizId'
      preLoaderRoute: typeof ViewQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings_/avatar': {
      id: '/account/settings_/avatar'
      path: '/account/settings/avatar'
      fullPath: '/account/settings/avatar'
      preLoaderRoute: typeof AccountSettingsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings_/security': {
      id: '/account/settings_/security'
      path: '/account/settings/security'
      fullPath: '/account/settings/security'
      preLoaderRoute: typeof AccountSettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  ImportRoute: ImportRoute,
  PlayRoute: PlayRoute,
  ResultsRoute: ResultsRoute,
  SearchRoute: SearchRoute,
  StyleguideRoute: StyleguideRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountOauthErrorRoute: AccountOauthErrorRoute,
  AccountPasswordResetRoute: AccountPasswordResetRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  DocsAttributionRoute: DocsAttributionRoute,
  DocsPrivacyPolicyRoute: DocsPrivacyPolicyRoute,
  EditFilesRoute: EditFilesRoute,
  QuiztivityEditRoute: QuiztivityEditRoute,
  QuiztivityPlayRoute: QuiztivityPlayRoute,
  UserUserIdRoute: UserUserIdRoute,
  ViewQuizIdRoute: ViewQuizIdRoute,
  DocsIndexRoute: DocsIndexRoute,
  EditIndexRoute: EditIndexRoute,
  AccountSettingsAvatarRoute: AccountSettingsAvatarRoute,
  AccountSettingsSecurityRoute: AccountSettingsSecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
